#!/usr/bin/env bash
exists()
{
  command -v "$1" >/dev/null 2>&1
}

exit_with_message()
{
  MESSAGE=$1

  TITLE='A problem has ocurred'
  CALL_ZENITY='zenity --error --text "$MESSAGE" --title "$TITLE"'
  CALL_KDIALOG='kdialog --error "$MESSAGE" --title "$TITLE"'
  CALL_XMESSAGE='xmessage "$MESSAGE" -nearmouse'

  # Check if GDMSESSION is set; if not, check tool availability
  # (kdialog first, since it's the least common):
  if [ -z ${GDMSESSION+x} ]; then
    if exists kdialog; then eval $CALL_KDIALOG
    elif exists zenity; then eval $CALL_ZENITY
    fi

    exit -1

  # Then, check desktop environment:
  elif
    [ $GDMSESSION = "ubuntu" ] ||
    [ $GDMSESSION = "ubuntu-2d" ] ||
    [ $GDMSESSION = "gnome-shell" ] ||
    [ $GDMSESSION = "gnome-classic" ] ||
    [ $GDMSESSION = "gnome-fallback" ] ||
    [ $GDMSESSION = "cinnamon" ] ||
    [ $GDMSESSION = "default" ] ||
    [ $GDMSESSION = "Lubuntu" ] ||
    [ $GDMSESSION = "xfce" ] &&
    exists zenity; then eval $CALL_ZENITY
  elif
    [ $GDMSESSION="kde-plasma" ] &&
    exists kdialog; then eval $CALL_KDIALOG

  # If all fails, fallback to xmessage
  else eval $CALL_XMESSAGE
  fi

  exit -1
}

if [ $(uname -m) != 'x86_64' ]; then
  exit_with_message "HitLeap Viewer only supports 64-bit Linux systems (x86_64)"
elif ! xset q &>/dev/null; then
  echo "No X server at \$DISPLAY [$DISPLAY]" >&2
  exit -1
fi

APP_DIR="$(cd "$(dirname "$0")"; pwd)"
OLD_PWD=$PWD

cd "$APP_DIR"

./lua HitLeap-Viewer.lua Linux $@

cd $OLD_PWD
